// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAlertLog = `-- name: InsertAlertLog :exec
INSERT INTO alert_logs (id, node_id, zone_name, factor_of_safety, level, channel, recipient, message, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAlertLogParams struct {
	ID             string             `json:"id"`
	NodeID         pgtype.Text        `json:"node_id"`
	ZoneName       string             `json:"zone_name"`
	FactorOfSafety pgtype.Numeric     `json:"factor_of_safety"`
	Level          string             `json:"level"`
	Channel        string             `json:"channel"`
	Recipient      string             `json:"recipient"`
	Message        string             `json:"message"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) InsertAlertLog(ctx context.Context, arg InsertAlertLogParams) error {
	_, err := q.db.Exec(ctx, insertAlertLog,
		arg.ID,
		arg.NodeID,
		arg.ZoneName,
		arg.FactorOfSafety,
		arg.Level,
		arg.Channel,
		arg.Recipient,
		arg.Message,
		arg.SentAt,
	)
	return err
}

const listRecentAlerts = `-- name: ListRecentAlerts :many
SELECT id, node_id, zone_name, factor_of_safety, level, channel, recipient, message, sent_at
FROM alert_logs
ORDER BY sent_at DESC
LIMIT $1
`

func (q *Queries) ListRecentAlerts(ctx context.Context, limitCount int32) ([]AlertLog, error) {
	rows, err := q.db.Query(ctx, listRecentAlerts, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertLog
	for rows.Next() {
		var i AlertLog
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ZoneName,
			&i.FactorOfSafety,
			&i.Level,
			&i.Channel,
			&i.Recipient,
			&i.Message,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
