// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: breaches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBreach = `-- name: InsertBreach :exec
INSERT INTO breach_records (id, reach_id, location_name, river, geom, breach_date, breach_width_m,
                            peak_discharge_m3s, failure_mechanism, impact_description, remediation_status, severity)
VALUES ($1, $2, $3, $4, ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326), $7, $8,
        $9, $10, $11, $12, $13)
ON CONFLICT (id) DO NOTHING
`

type InsertBreachParams struct {
	ID                string         `json:"id"`
	ReachID           pgtype.Text    `json:"reach_id"`
	LocationName      string         `json:"location_name"`
	River             string         `json:"river"`
	Longitude         float64        `json:"longitude"`
	Latitude          float64        `json:"latitude"`
	BreachDate        pgtype.Date    `json:"breach_date"`
	BreachWidthM      pgtype.Numeric `json:"breach_width_m"`
	PeakDischargeM3s  pgtype.Numeric `json:"peak_discharge_m3s"`
	FailureMechanism  string         `json:"failure_mechanism"`
	ImpactDescription pgtype.Text    `json:"impact_description"`
	RemediationStatus string         `json:"remediation_status"`
	Severity          string         `json:"severity"`
}

func (q *Queries) InsertBreach(ctx context.Context, arg InsertBreachParams) error {
	_, err := q.db.Exec(ctx, insertBreach,
		arg.ID,
		arg.ReachID,
		arg.LocationName,
		arg.River,
		arg.Longitude,
		arg.Latitude,
		arg.BreachDate,
		arg.BreachWidthM,
		arg.PeakDischargeM3s,
		arg.FailureMechanism,
		arg.ImpactDescription,
		arg.RemediationStatus,
		arg.Severity,
	)
	return err
}

const listBreaches = `-- name: ListBreaches :many
SELECT id, reach_id, location_name, river, ST_X(geom) AS longitude, ST_Y(geom) AS latitude,
       breach_date, breach_width_m, peak_discharge_m3s, failure_mechanism, impact_description,
       remediation_status, severity
FROM breach_records
ORDER BY breach_date DESC
`

type ListBreachesRow struct {
	ID                string         `json:"id"`
	ReachID           pgtype.Text    `json:"reach_id"`
	LocationName      string         `json:"location_name"`
	River             string         `json:"river"`
	Longitude         interface{}    `json:"longitude"`
	Latitude          interface{}    `json:"latitude"`
	BreachDate        pgtype.Date    `json:"breach_date"`
	BreachWidthM      pgtype.Numeric `json:"breach_width_m"`
	PeakDischargeM3s  pgtype.Numeric `json:"peak_discharge_m3s"`
	FailureMechanism  string         `json:"failure_mechanism"`
	ImpactDescription pgtype.Text    `json:"impact_description"`
	RemediationStatus string         `json:"remediation_status"`
	Severity          string         `json:"severity"`
}

func (q *Queries) ListBreaches(ctx context.Context) ([]ListBreachesRow, error) {
	rows, err := q.db.Query(ctx, listBreaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBreachesRow
	for rows.Next() {
		var i ListBreachesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReachID,
			&i.LocationName,
			&i.River,
			&i.Longitude,
			&i.Latitude,
			&i.BreachDate,
			&i.BreachWidthM,
			&i.PeakDischargeM3s,
			&i.FailureMechanism,
			&i.ImpactDescription,
			&i.RemediationStatus,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
