// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: macro.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestMacroReadingForReach = `-- name: GetLatestMacroReadingForReach :one
SELECT time, reach_id, sar_backscatter_db, sar_water_detected,
       optical_mndwi, optical_ndvi, cwc_water_level_m, cwc_danger_level_m,
       freeboard_m, rate_of_rise_cm_h, rainfall_72h_mm, hydraulic_warning
FROM macro_readings
WHERE reach_id = $1
ORDER BY time DESC
LIMIT 1
`

func (q *Queries) GetLatestMacroReadingForReach(ctx context.Context, reachID string) (MacroReading, error) {
	row := q.db.QueryRow(ctx, getLatestMacroReadingForReach, reachID)
	var i MacroReading
	err := row.Scan(
		&i.Time,
		&i.ReachID,
		&i.SarBackscatterDb,
		&i.SarWaterDetected,
		&i.OpticalMndwi,
		&i.OpticalNdvi,
		&i.CwcWaterLevelM,
		&i.CwcDangerLevelM,
		&i.FreeboardM,
		&i.RateOfRiseCmH,
		&i.Rainfall72hMm,
		&i.HydraulicWarning,
	)
	return i, err
}

const insertMacroReading = `-- name: InsertMacroReading :exec
INSERT INTO macro_readings (time, reach_id, sar_backscatter_db, sar_water_detected,
                            optical_mndwi, optical_ndvi, cwc_water_level_m, cwc_danger_level_m,
                            freeboard_m, rate_of_rise_cm_h, rainfall_72h_mm, hydraulic_warning)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12)
`

type InsertMacroReadingParams struct {
	Time             pgtype.Timestamptz `json:"time"`
	ReachID          string             `json:"reach_id"`
	SarBackscatterDb pgtype.Numeric     `json:"sar_backscatter_db"`
	SarWaterDetected pgtype.Bool        `json:"sar_water_detected"`
	OpticalMndwi     pgtype.Numeric     `json:"optical_mndwi"`
	OpticalNdvi      pgtype.Numeric     `json:"optical_ndvi"`
	CwcWaterLevelM   pgtype.Numeric     `json:"cwc_water_level_m"`
	CwcDangerLevelM  pgtype.Numeric     `json:"cwc_danger_level_m"`
	FreeboardM       pgtype.Numeric     `json:"freeboard_m"`
	RateOfRiseCmH    pgtype.Numeric     `json:"rate_of_rise_cm_h"`
	Rainfall72hMm    pgtype.Numeric     `json:"rainfall_72h_mm"`
	HydraulicWarning pgtype.Bool        `json:"hydraulic_warning"`
}

func (q *Queries) InsertMacroReading(ctx context.Context, arg InsertMacroReadingParams) error {
	_, err := q.db.Exec(ctx, insertMacroReading,
		arg.Time,
		arg.ReachID,
		arg.SarBackscatterDb,
		arg.SarWaterDetected,
		arg.OpticalMndwi,
		arg.OpticalNdvi,
		arg.CwcWaterLevelM,
		arg.CwcDangerLevelM,
		arg.FreeboardM,
		arg.RateOfRiseCmH,
		arg.Rainfall72hMm,
		arg.HydraulicWarning,
	)
	return err
}
