// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertLog struct {
	ID             string             `json:"id"`
	NodeID         pgtype.Text        `json:"node_id"`
	ZoneName       string             `json:"zone_name"`
	FactorOfSafety pgtype.Numeric     `json:"factor_of_safety"`
	Level          string             `json:"level"`
	Channel        string             `json:"channel"`
	Recipient      string             `json:"recipient"`
	Message        string             `json:"message"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

type BreachRecord struct {
	ID                string         `json:"id"`
	ReachID           pgtype.Text    `json:"reach_id"`
	LocationName      string         `json:"location_name"`
	River             string         `json:"river"`
	Geom              interface{}    `json:"geom"`
	BreachDate        pgtype.Date    `json:"breach_date"`
	BreachWidthM      pgtype.Numeric `json:"breach_width_m"`
	PeakDischargeM3s  pgtype.Numeric `json:"peak_discharge_m3s"`
	FailureMechanism  string         `json:"failure_mechanism"`
	ImpactDescription pgtype.Text    `json:"impact_description"`
	RemediationStatus string         `json:"remediation_status"`
	Severity          string         `json:"severity"`
}

type EmbankmentNode struct {
	NodeID         string             `json:"node_id"`
	ZoneName       string             `json:"zone_name"`
	River          string             `json:"river"`
	Geom           interface{}        `json:"geom"`
	ElevationM     pgtype.Numeric     `json:"elevation_m"`
	BatteryVoltage pgtype.Numeric     `json:"battery_voltage"`
	FirmwareVer    string             `json:"firmware_ver"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
}

type EmbankmentReach struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	River          string         `json:"river"`
	District       string         `json:"district"`
	LengthKm       pgtype.Numeric `json:"length_km"`
	CrestElevation pgtype.Numeric `json:"crest_elevation"`
	BaseWidthM     pgtype.Numeric `json:"base_width_m"`
	EmbankmentType string         `json:"embankment_type"`
	Vulnerable     pgtype.Bool    `json:"vulnerable"`
	ActiveNodeID   pgtype.Text    `json:"active_node_id"`
	Centerline     interface{}    `json:"centerline"`
	Buffer50m      interface{}    `json:"buffer_50m"`
	LastSurveyDate pgtype.Date    `json:"last_survey_date"`
}

type MacroReading struct {
	Time             pgtype.Timestamptz `json:"time"`
	ReachID          string             `json:"reach_id"`
	SarBackscatterDb pgtype.Numeric     `json:"sar_backscatter_db"`
	SarWaterDetected pgtype.Bool        `json:"sar_water_detected"`
	OpticalMndwi     pgtype.Numeric     `json:"optical_mndwi"`
	OpticalNdvi      pgtype.Numeric     `json:"optical_ndvi"`
	CwcWaterLevelM   pgtype.Numeric     `json:"cwc_water_level_m"`
	CwcDangerLevelM  pgtype.Numeric     `json:"cwc_danger_level_m"`
	FreeboardM       pgtype.Numeric     `json:"freeboard_m"`
	RateOfRiseCmH    pgtype.Numeric     `json:"rate_of_rise_cm_h"`
	Rainfall72hMm    pgtype.Numeric     `json:"rainfall_72h_mm"`
	HydraulicWarning pgtype.Bool        `json:"hydraulic_warning"`
}

type NodeTelemetry struct {
	Time           pgtype.Timestamptz `json:"time"`
	NodeID         string             `json:"node_id"`
	SoilMoisture   pgtype.Numeric     `json:"soil_moisture"`
	TiltAngle      pgtype.Numeric     `json:"tilt_angle"`
	AudioRms       pgtype.Numeric     `json:"audio_rms"`
	FactorOfSafety pgtype.Numeric     `json:"factor_of_safety"`
	Status         string             `json:"status"`
}
