// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNode = `-- name: GetNode :one
SELECT node_id, zone_name, river, ST_X(geom) AS longitude, ST_Y(geom) AS latitude,
       elevation_m, battery_voltage, firmware_ver, created_at, last_seen
FROM embankment_nodes
WHERE node_id = $1
`

type GetNodeRow struct {
	NodeID         string             `json:"node_id"`
	ZoneName       string             `json:"zone_name"`
	River          string             `json:"river"`
	Longitude      interface{}        `json:"longitude"`
	Latitude       interface{}        `json:"latitude"`
	ElevationM     pgtype.Numeric     `json:"elevation_m"`
	BatteryVoltage pgtype.Numeric     `json:"battery_voltage"`
	FirmwareVer    string             `json:"firmware_ver"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) GetNode(ctx context.Context, nodeID string) (GetNodeRow, error) {
	row := q.db.QueryRow(ctx, getNode, nodeID)
	var i GetNodeRow
	err := row.Scan(
		&i.NodeID,
		&i.ZoneName,
		&i.River,
		&i.Longitude,
		&i.Latitude,
		&i.ElevationM,
		&i.BatteryVoltage,
		&i.FirmwareVer,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO embankment_nodes (node_id, zone_name, river, geom, elevation_m, battery_voltage, firmware_ver, last_seen)
VALUES ($1, $2, $3, ST_SetSRID(ST_MakePoint($4::float8, $5::float8), 4326), $6, $7, $8, $9)
ON CONFLICT (node_id) DO UPDATE SET
    zone_name = EXCLUDED.zone_name,
    battery_voltage = EXCLUDED.battery_voltage,
    last_seen = EXCLUDED.last_seen
`

type InsertNodeParams struct {
	NodeID         string             `json:"node_id"`
	ZoneName       string             `json:"zone_name"`
	River          string             `json:"river"`
	Longitude      float64            `json:"longitude"`
	Latitude       float64            `json:"latitude"`
	ElevationM     pgtype.Numeric     `json:"elevation_m"`
	BatteryVoltage pgtype.Numeric     `json:"battery_voltage"`
	FirmwareVer    string             `json:"firmware_ver"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.Exec(ctx, insertNode,
		arg.NodeID,
		arg.ZoneName,
		arg.River,
		arg.Longitude,
		arg.Latitude,
		arg.ElevationM,
		arg.BatteryVoltage,
		arg.FirmwareVer,
		arg.LastSeen,
	)
	return err
}

const listNodes = `-- name: ListNodes :many
SELECT node_id, zone_name, river, ST_X(geom) AS longitude, ST_Y(geom) AS latitude,
       elevation_m, battery_voltage, firmware_ver, created_at, last_seen
FROM embankment_nodes
ORDER BY node_id ASC
`

type ListNodesRow struct {
	NodeID         string             `json:"node_id"`
	ZoneName       string             `json:"zone_name"`
	River          string             `json:"river"`
	Longitude      interface{}        `json:"longitude"`
	Latitude       interface{}        `json:"latitude"`
	ElevationM     pgtype.Numeric     `json:"elevation_m"`
	BatteryVoltage pgtype.Numeric     `json:"battery_voltage"`
	FirmwareVer    string             `json:"firmware_ver"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) ListNodes(ctx context.Context) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesRow
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.ZoneName,
			&i.River,
			&i.Longitude,
			&i.Latitude,
			&i.ElevationM,
			&i.BatteryVoltage,
			&i.FirmwareVer,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
