// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetAllReaches(ctx context.Context) ([]GetAllReachesRow, error)
	GetLatestMacroReadingForReach(ctx context.Context, reachID string) (MacroReading, error)
	GetLatestTelemetryForNode(ctx context.Context, nodeID string) (NodeTelemetry, error)
	GetNode(ctx context.Context, nodeID string) (GetNodeRow, error)
	GetRecentTelemetryHistory(ctx context.Context, arg GetRecentTelemetryHistoryParams) ([]NodeTelemetry, error)
	InsertAlertLog(ctx context.Context, arg InsertAlertLogParams) error
	InsertBreach(ctx context.Context, arg InsertBreachParams) error
	InsertMacroReading(ctx context.Context, arg InsertMacroReadingParams) error
	InsertNode(ctx context.Context, arg InsertNodeParams) error
	InsertNodeTelemetry(ctx context.Context, arg InsertNodeTelemetryParams) error
	InsertReach(ctx context.Context, arg InsertReachParams) error
	ListBreaches(ctx context.Context) ([]ListBreachesRow, error)
	ListNodes(ctx context.Context) ([]ListNodesRow, error)
	ListRecentAlerts(ctx context.Context, limitCount int32) ([]AlertLog, error)
}

var _ Querier = (*Queries)(nil)
