// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reaches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllReaches = `-- name: GetAllReaches :many
SELECT id, name, river, district, length_km, crest_elevation, base_width_m,
       embankment_type, vulnerable, active_node_id,
       ST_AsGeoJSON(centerline)::text AS centerline_geojson,
       ST_AsGeoJSON(buffer_50m)::text AS buffer_geojson,
       last_survey_date
FROM embankment_reaches
ORDER BY id ASC
`

type GetAllReachesRow struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	River             string         `json:"river"`
	District          string         `json:"district"`
	LengthKm          pgtype.Numeric `json:"length_km"`
	CrestElevation    pgtype.Numeric `json:"crest_elevation"`
	BaseWidthM        pgtype.Numeric `json:"base_width_m"`
	EmbankmentType    string         `json:"embankment_type"`
	Vulnerable        pgtype.Bool    `json:"vulnerable"`
	ActiveNodeID      pgtype.Text    `json:"active_node_id"`
	CenterlineGeojson string         `json:"centerline_geojson"`
	BufferGeojson     string         `json:"buffer_geojson"`
	LastSurveyDate    pgtype.Date    `json:"last_survey_date"`
}

func (q *Queries) GetAllReaches(ctx context.Context) ([]GetAllReachesRow, error) {
	rows, err := q.db.Query(ctx, getAllReaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReachesRow
	for rows.Next() {
		var i GetAllReachesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.River,
			&i.District,
			&i.LengthKm,
			&i.CrestElevation,
			&i.BaseWidthM,
			&i.EmbankmentType,
			&i.Vulnerable,
			&i.ActiveNodeID,
			&i.CenterlineGeojson,
			&i.BufferGeojson,
			&i.LastSurveyDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReach = `-- name: InsertReach :exec
INSERT INTO embankment_reaches (id, name, river, district, length_km, crest_elevation, base_width_m,
                                embankment_type, vulnerable, active_node_id, centerline, buffer_50m, last_survey_date)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, ST_GeomFromGeoJSON($11::text), ST_GeomFromGeoJSON($12::text), $13)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    vulnerable = EXCLUDED.vulnerable,
    last_survey_date = EXCLUDED.last_survey_date
`

type InsertReachParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	River          string         `json:"river"`
	District       string         `json:"district"`
	LengthKm       pgtype.Numeric `json:"length_km"`
	CrestElevation pgtype.Numeric `json:"crest_elevation"`
	BaseWidthM     pgtype.Numeric `json:"base_width_m"`
	EmbankmentType string         `json:"embankment_type"`
	Vulnerable     pgtype.Bool    `json:"vulnerable"`
	ActiveNodeID   pgtype.Text    `json:"active_node_id"`
	CenterlineJson string         `json:"centerline_json"`
	BufferJson     string         `json:"buffer_json"`
	LastSurveyDate pgtype.Date    `json:"last_survey_date"`
}

func (q *Queries) InsertReach(ctx context.Context, arg InsertReachParams) error {
	_, err := q.db.Exec(ctx, insertReach,
		arg.ID,
		arg.Name,
		arg.River,
		arg.District,
		arg.LengthKm,
		arg.CrestElevation,
		arg.BaseWidthM,
		arg.EmbankmentType,
		arg.Vulnerable,
		arg.ActiveNodeID,
		arg.CenterlineJson,
		arg.BufferJson,
		arg.LastSurveyDate,
	)
	return err
}
