// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestTelemetryForNode = `-- name: GetLatestTelemetryForNode :one
SELECT time, node_id, soil_moisture, tilt_angle, audio_rms, factor_of_safety, status
FROM node_telemetry
WHERE node_id = $1
ORDER BY time DESC
LIMIT 1
`

func (q *Queries) GetLatestTelemetryForNode(ctx context.Context, nodeID string) (NodeTelemetry, error) {
	row := q.db.QueryRow(ctx, getLatestTelemetryForNode, nodeID)
	var i NodeTelemetry
	err := row.Scan(
		&i.Time,
		&i.NodeID,
		&i.SoilMoisture,
		&i.TiltAngle,
		&i.AudioRms,
		&i.FactorOfSafety,
		&i.Status,
	)
	return i, err
}

const getRecentTelemetryHistory = `-- name: GetRecentTelemetryHistory :many
SELECT time, node_id, soil_moisture, tilt_angle, audio_rms, factor_of_safety, status
FROM node_telemetry
WHERE ($1::text = '' OR node_id = $1)
ORDER BY time DESC
LIMIT $2
`

type GetRecentTelemetryHistoryParams struct {
	NodeID     string `json:"node_id"`
	LimitCount int32  `json:"limit_count"`
}

func (q *Queries) GetRecentTelemetryHistory(ctx context.Context, arg GetRecentTelemetryHistoryParams) ([]NodeTelemetry, error) {
	rows, err := q.db.Query(ctx, getRecentTelemetryHistory, arg.NodeID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeTelemetry
	for rows.Next() {
		var i NodeTelemetry
		if err := rows.Scan(
			&i.Time,
			&i.NodeID,
			&i.SoilMoisture,
			&i.TiltAngle,
			&i.AudioRms,
			&i.FactorOfSafety,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNodeTelemetry = `-- name: InsertNodeTelemetry :exec
INSERT INTO node_telemetry (time, node_id, soil_moisture, tilt_angle, audio_rms, factor_of_safety, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNodeTelemetryParams struct {
	Time           pgtype.Timestamptz `json:"time"`
	NodeID         string             `json:"node_id"`
	SoilMoisture   pgtype.Numeric     `json:"soil_moisture"`
	TiltAngle      pgtype.Numeric     `json:"tilt_angle"`
	AudioRms       pgtype.Numeric     `json:"audio_rms"`
	FactorOfSafety pgtype.Numeric     `json:"factor_of_safety"`
	Status         string             `json:"status"`
}

func (q *Queries) InsertNodeTelemetry(ctx context.Context, arg InsertNodeTelemetryParams) error {
	_, err := q.db.Exec(ctx, insertNodeTelemetry,
		arg.Time,
		arg.NodeID,
		arg.SoilMoisture,
		arg.TiltAngle,
		arg.AudioRms,
		arg.FactorOfSafety,
		arg.Status,
	)
	return err
}
